dist: bionic

language: python

sudo:  false

python:
  - "3.6"
  - "3.7"

cache: pip

install: "pip install -r requirements.txt"

before_script: cd tests

script: python test_all.py


notifications:
  email: williamjudge94@gmail.com